config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items, only: [:create, :destroy]
  resources :carts, only: [:show]
  # get 'top/main'
  # get 'products/index'
  # get 'products/new'
  # get 'carts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :CartItems
    has_many :CartItem_Products, through: :CartItems, source: :Product
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :CartItem
    has_one :CartItem_Cart, through: :CartItem, source: :Cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
private
   def current_cart
      if session[:cart_id]
        cart = Cart.find(session[:cart_id])
      else
        cart = Cart.create
        session[:cart_id] = cart.id
      end
     cart
   end
  helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def create
        
    end
    
    def destroy
        
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = current_cart.cart_item
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(
      name: params[:product][:name],
      price: params[:product][:price])
    if @product.save
      flash[:info] = "商品を登録しました"
      redirect_to products_path
    else
      render :new
    end
  end
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    flash[:info] = "商品を削除しました"
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>

<% if flash[:info] %>
  <font color="green"><%= flash[:info] %></font>
<% end %>

<% @products.each do |e| %>
  <p>
      <%= e.name %>
      <%= e.price %>円
      <%= link_to '削除', product_path(e), method: :delete %>
  </p>
<% end %>

<hr>

<%= link_to '商品追加', new_product_path %>

app/views/products/new.html.erb
<h1>商品登録</h1>

<% if @product.errors.present? %>
<font color="red">
    <h3>エラーがあります</h3>
    <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
    </font>
<% end %>

<%= form_for @product, url: {action: :create} do |f| %>
   <p>  
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name %>
   </p>
   <p>
      <%= f.label :price, '値段' %>
      <%= f.text_field :price %>
   </p>
   <p>
      <%= f.submit '登録' %>
   </p>
<% end %>

app/views/top/main.html.erb
<h1>商品</h1>

<% @products.each do |e| %>
  <p>
      <%= e.name %>
      <%= e.price %>円
      <%= link_to 'カートに入れる', cart_items_path(product_id: e.id), method: :post %>
      <%= link_to 'カートから削除', cart_item_path(e), method: :delete %>
  </p>
  
<% end %>
<%= link_to 'カート', cart_path(current_cart) %>